iface0: 'usbnet0'
iface1: 'usbnet1'
management_int: 'eth0'
wwan_int: ''
wwan_apn: 'vzwinternet'
radio_silence: 'OFF'
enable_ipv6: 'OFF'
client_ip: ''
client_mac: ''
gateway_ip: ''
gateway_mac: ''
domain_name: ''
dns_server: ''
auto_run: {switch: 'TRUE', command: 'python /root/tools/dolos_cloak/launcher.py'}
